vitess:
  topology:
    cells:
      - name: "zone1"
        etcd:
          replicas: 1
        vtctld:
          replicas: 1
        vtgate:
          replicas: 1
        mysqlProtocol:
          enabled: true
          authType: "none"
        keyspaces:
          - name: "commerce"
            shards:
              - name: "0"
                tablets:
                  - type: "replica"
                    vttablet:
                      replicas: 2
                  - type: "rdonly"
                    vttablet:
                      replicas: 1
            schema:
              initial: |-
                create table product(
                  sku varbinary(128),
                  description varbinary(128),
                  price bigint,
                  primary key(sku)
                );
                create table customer(
                  customer_id bigint not null auto_increment,
                  email varbinary(128),
                  primary key(customer_id)
                );
                create table corder(
                  order_id bigint not null auto_increment,
                  customer_id bigint,
                  sku varbinary(128),
                  price bigint,
                  primary key(order_id)
                );
            vschema:
              initial: |-
                {
                  "tables": {
                    "product": {},
                    "customer": {},
                    "corder": {}
                  }
                }

  etcd:
    replicas: 1
    resources:

  vtctld:
    serviceType: "NodePort"
    resources:

  vtgate:
    serviceType: "NodePort"
    resources:

  vttablet:
    mysqlSize: "test"
    resources:
    mysqlResources:

  vtworker:
    resources:

  pmm:
    enabled: false

  orchestrator:
    enabled: false

  config:
    backup:
      backup_storage_implementation: {}
      gcs_backup_storage_bucket: {}
      gcs_backup_storage_root: {}
      s3_backup_aws_region: {}
      s3_backup_storage_bucket: {}
      s3_backup_storage_root: {}
      s3_backup_server_side_encryption: {}