---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: liftbridge
  namespace: processor
  labels:
    app: liftbridge
spec:
  replicas: 3
  updateStrategy:
    type: RollingUpdate
  serviceName: liftbridge
  selector:
    matchLabels:
      app: liftbridge
  template:
    metadata:
      labels:
        app: liftbridge
    spec:
      containers:
        - name: liftbridge
          image: liftbridge/liftbridge-docker:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "100m"
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          args:
            - "liftbridge"
            - "--nats-servers=processor-nats-liftbridge:4222"
            - "--id=$(POD_NAME)"
            - "--raft-bootstrap-seed"
          ports:
            - containerPort: 4222
            - containerPort: 6222
            - containerPort: 8222
            - containerPort: 9292
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    app: "liftbridge"

---
apiVersion: v1
kind: Service
metadata:
  name: liftbridge
  namespace: processor
spec:
  selector:
    app: liftbridge
  ports:
    - name: nats-client
      port: 4222
    - name: nats-clustering
      port: 6222
    - name: nats-mgmt
      port: 8222
    - name: liftbridge-client
      port: 9292
