---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: processor-stan
  namespace: processor
  labels:
    app: processor-stan
spec:
  replicas: 5
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: processor-stan
  serviceName: processor-stan
  template:
    metadata:
      labels:
        app: "processor-stan"
      annotations: {}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  app: "processor-stan"
      containers:
        - name: processor-stan
          image: docker.io/nats-streaming:0.16.2
          imagePullPolicy: IfNotPresent
          env:
          - name: POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          args: [
            "-clustered",
            "-cid", "processor-core",
            "-m",   "8222",
            "-ns",  "nats://processor-nats-cluster:4222",
            "-mc",  "100",
            "-msu", "1000",
            "-mm",  "1000000",
            "-mb",  "900mb",
            "-ma",  "0",
            "-hbi", "30s",
            "-hbt", "10s",
            "-hbf", "330",

            "--cluster_node_id", "$(POD_NAME)",
            "--cluster_peers", "processor-stan-0,processor-stan-1,processor-stan-2,processor-stan-3,processor-stan-4",
            "--store", "file",
            "--dir", "/nats/processor-stan/$(POD_NAME)/data",
            "--cluster_log_path", "/nats/processor-stan/$(POD_NAME)/raft",
            "--file_compact_enabled",
            "--file_compact_frag", "50",
            "--file_compact_interval", "300",
            "--file_compact_min_size", "1048576",
            "--file_buffer_size", "2097152",
            "--file_crc",
            "--file_crc_poly", "3988292384",
            "--file_sync",
            "--file_slice_max_msgs", "0",
            "--file_slice_max_bytes", "67108931",
            "--file_slice_max_age", "0",
            "--file_fds_limit", "0",
            "--file_parallel_recovery", "1",
          ]
          ports:
            - name: monitoring
              containerPort: 8222
          volumeMounts:
            - name: datadir
              mountPath: /nats
          livenessProbe:
            httpGet:
              path: /
              port: monitoring
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /
              port: monitoring
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            successThreshold: 1
            failureThreshold: 6

      volumes:
        # TODO: Update this with a persistent storage
        - name: datadir
          emptyDir: {}

---
apiVersion: v1
kind: Service
metadata:
  name: processor-stan
  namespace: processor
  labels:
    app: processor-stan
  annotations: {}
spec:
  type: ClusterIP
  selector:
    app: processor-stan
  ports:
  - name: processor-stan
    port: 8222
