env: prod

# === Application Onboarding with ArgoCD ==================================== #
#
#   Once you provide the `key`, ArgoCD template setup is going to search
#   for the same name directory inside `get-gitops-k8s/stack/`. If the
#   boolean value is set to `true`, ArgoCD will ignore.
#
#   If `stack` does not comply with the directory format ArgoCD expects,
#   ArgoCD sync will be halted until it is fixed.
#
apps:
  argo-workflows: false
  etcd-operator: false
  falco: false
  istio: true
  nats-jetstream: false
  playground: false
  sealed-secrets: false
  tekton-pipeline: false
  vault: false
  vitess: false
#
# =========================================================================== #

# === ArgoCD Setup ========================================================== #
#
# Metadata
metadata:
  finalizers:
    enabled: true
# Overrides
spec:
  source:
    gitRepoUrl: https://github.com/rytswd/get-gitops-k8s.git
    targetRevision: prod
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune:
        # Specifies if resources should be pruned during auto-syncing
        # ( false by default ).
        enabled: true
      selfHeal:
        # Specifies if partial app sync should be executed when resources
        # are changed only in target Kubernetes cluster and no git change
        # detected ( false by default ).
        enabled: true
#
# =========================================================================== #
