env: prod

falco:
  enabled: false
nats:
  enabled: true
sealed-secrets:
  enabled: true

metadata:
  finalizers:
    enabled: true

spec:
  source:
    targetRevision: prod # This assumes 'prod' branch or tag exists
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune:
        enabled: true # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal:
        enabled: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
